# fly.toml app configuration file for ecopay-api
app = 'ecopay-api'
primary_region = 'jnb'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3001'
  SUPABASE_URL = 'https://drkjkkpzujwnkghtdokz.supabase.co'
  BYBIT_BASE_URL = 'https://api.bybit.com'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[secrets]]
  key = "SUPABASE_SERVICE_ROLE_KEY"
[[secrets]]
  key = "BYBIT_API_KEY"
[[secrets]]
  key = "BYBIT_API_SECRET"
